definitions:
  io.AdminInfoOutput:
    properties:
      avatar:
        type: string
      id:
        type: integer
      intro:
        type: string
      login_time:
        type: string
      roles:
        items:
          type: string
        type: array
      user_name:
        type: string
    type: object
  io.AdminLoginInput:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  io.AdminLoginOutput:
    properties:
      token:
        example: token
        type: string
    type: object
  io.ChangePwdInput:
    properties:
      password:
        example: "123456"
        type: string
    required:
    - password
    type: object
  io.ServiceAddHTTPInput:
    properties:
      black_list:
        type: string
      client_ip_flow_limit:
        type: integer
      head_transform:
        type: string
      ip_list:
        type: string
      need_https:
        type: integer
      need_strip_uri:
        type: integer
      need_websocket:
        type: integer
      open_auth:
        type: integer
      round_type:
        type: integer
      rule:
        type: string
      rule_type:
        type: integer
      service_desc:
        type: string
      service_flow_limit:
        type: integer
      service_name:
        description: ID            int64  `json:"id" form:"id" comment:"Service id"
          example:"56" validate:"required,min=1"`
        type: string
      upstream_connect_time_out:
        type: integer
      upstream_header_time_out:
        type: integer
      upstream_idle_time_out:
        type: integer
      upstream_max_idle:
        type: integer
      url_rewrite:
        type: string
      weight_list:
        type: string
      white_list:
        type: string
    required:
    - ip_list
    - rule
    - service_desc
    - service_name
    - weight_list
    type: object
  io.ServiceListItemOutput:
    properties:
      id:
        type: integer
      load_type:
        type: integer
      qpd:
        type: integer
      qps:
        type: integer
      service_addr:
        type: string
      service_desc:
        type: string
      service_name:
        type: string
      total_node:
        type: integer
    type: object
  io.ServiceListOutput:
    properties:
      list:
        items:
          $ref: '#/definitions/io.ServiceListItemOutput'
        type: array
      total:
        type: integer
    type: object
  io.ServiceUpdateHTTPInput:
    properties:
      black_list:
        type: string
      client_ip_flow_limit:
        type: integer
      head_transform:
        type: string
      id:
        example: 56
        type: integer
      ip_list:
        example: 127.0.0.1:80
        type: string
      need_https:
        type: integer
      need_strip_uri:
        type: integer
      need_websocket:
        type: integer
      open_auth:
        type: integer
      round_type:
        type: integer
      rule:
        type: string
      rule_type:
        type: integer
      service_desc:
        example: test_add_http
        type: string
      service_flow_limit:
        type: integer
      service_name:
        example: test_add_http
        type: string
      upstream_connect_time_out:
        type: integer
      upstream_header_time_out:
        type: integer
      upstream_idle_time_out:
        type: integer
      upstream_max_idle:
        type: integer
      url_rewrite:
        type: string
      weight_list:
        example: "50"
        type: string
      white_list:
        type: string
    required:
    - id
    - ip_list
    - rule
    - service_desc
    - service_name
    - weight_list
    type: object
  middleware.Response:
    properties:
      data:
        type: object
      errmsg:
        type: string
      errno:
        type: integer
      stack:
        type: object
      trace_id:
        type: object
    type: object
info:
  contact: {}
paths:
  /admin/admin_info:
    get:
      consumes:
      - application/json
      description: Admin info.
      operationId: /admin/admin_info
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/io.AdminInfoOutput'
              type: object
      summary: Admin info.
      tags:
      - Admin API.
  /admin/change_pwd:
    post:
      consumes:
      - application/json
      description: Change admin password.
      operationId: /admin/change_pwd
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/io.ChangePwdInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Change admin password.
      tags:
      - Admin API.
  /admin_login/login:
    post:
      consumes:
      - application/json
      description: Admin login.
      operationId: /admin_login/login
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/io.AdminLoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/io.AdminLoginOutput'
              type: object
      summary: Admin login.
      tags:
      - Admin API.
  /admin_login/logout:
    get:
      consumes:
      - application/json
      description: Admin logout.
      operationId: /admin_login/logout
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Admin logout.
      tags:
      - Admin API.
  /service/service_add_http:
    post:
      consumes:
      - application/json
      description: Add HTTP service
      operationId: /service/service_add_http
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/io.ServiceAddHTTPInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Add HTTP service
      tags:
      - Service Management
  /service/service_delete:
    get:
      consumes:
      - application/json
      description: Delete a service.
      operationId: /service/service_delete
      parameters:
      - description: service id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Delete a service
      tags:
      - Service Management
  /service/service_list:
    get:
      consumes:
      - application/json
      description: Show service lists.
      operationId: /service/service_list
      parameters:
      - description: Searching keyword
        in: query
        name: info
        type: string
      - description: Entries per page
        in: query
        name: page_size
        required: true
        type: integer
      - description: Page No.
        in: query
        name: page_no
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/io.ServiceListOutput'
              type: object
      summary: Service list
      tags:
      - Service Management
  /service/service_update_http:
    post:
      consumes:
      - application/json
      description: Update HTTP service
      operationId: /service/service_update_http
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/io.ServiceUpdateHTTPInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Update HTTP service
      tags:
      - Service Management
swagger: "2.0"
